# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "../ubuntu1810-dev.box"

  config.vm.provision :shell, path: "./reduce.sh"

	config.vm.provider :virtualbox do |virtualbox|
		virtualbox.gui = true
		virtualbox.customize ["modifyvm", :id, "--name", "vagrant-dev"]
		virtualbox.customize ["modifyvm", :id, "--memory", "4096", "--cpus", "4", "--vram", "256"]
	end
end
